project_id = "zdvrqkdbhurpfiemwryc"

[functions.shopify-graphql]
verify_jwt = false

[functions.job-runner]
verify_jwt = false

[functions.printify-api]
verify_jwt = false

[functions.webhooks-ingest]
verify_jwt = false